services:
  mysql:
    image: mysql:8.0
    container_name: idcard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idcard_db
    ports:
      - "3307:3306"
    volumes:
      - idcard-mysql-data:/var/lib/mysql

volumes:
  idcard-mysql-data:
